### ISSUE TITLE
How run this application ?

### ISSUE THREAD

**Issue by Domovenok** [angryziber/simple-java#2]
Could you explain how can i run your application ? I do:
$ git clone https://github.com/angryziber/simple-java simple-java
$ cd simple-java
$ ant
$ cd src
$ javac -cp ../lib/default/_: Launcher.java
$ java -cp ../lib/default/_: Launcher

In chrome i write "http://localhost:8080/" . And i see:
HTTP ERROR: 503

Problem accessing /. Reason:

```
Service Unavailable
```

Powered by Jetty://

**Comment by angryziber** [comment]
Use the Launcher class from under the src. Normally you would run it from a Java IDE

**Comment by Domovenok** [comment]
When a run java -cp ../lib/default: Launcher , I am already in the src directory. I like to use console when i start something new for me ))

**Comment by angryziber** [comment]
Then you need to compile the classes first. If you are starting, I really
recommend an IDE :-)
Classpath definition should be more like this: -cp lib/default/*

**Comment by Domovenok** [comment]
Sorry, of course i am using java -cp ../lib/default/\* Launcher
Ok. I try to use IDEA IDE )

**Comment by Domovenok** [comment]
I still can not run application (( I create the project in IDEA. But when i try to Run Launcher, i get 81 errors. Here some errors: 
java: package javax.persistence does not exist

Before running application i run "ant" in root directory

**Comment by angryziber** [comment]
Try adding all jar files from the lib directory as dependencies to the
proect.

**Comment by Domovenok** [comment]
Thanks a lot. All works )))
